FROM registry.wellmatchhealth.com/alpine-node:4.2.2


ENV BOTDIR /opt/bot
ENV HUBOT_PORT 8080
ENV HUBOT_ADAPTER hipchat
ENV HUBOT_NAME databot
ENV HUBOT_AUTH_ADMIN wmh-devops
ENV HUBOT_HIPCHAT_RECONNECT true
ENV HUBOT_HIPCHAT_JOIN_PUBLIC_ROOMS false
ENV HUBOT_HIPCHAT_JOIN_ROOMS_ON_INVITE false
ENV HUBOT_HIPCHAT_ROOMS 20316_wm_chatops@conf.hipchat.com
ENV HUBOT_HIPCHAT_RECONNECT true

EXPOSE ${HUBOT_PORT}

ADD . ${BOTDIR}
WORKDIR ${BOTDIR}

RUN npm install

CMD bin/hubot
